### ISSUE TITLE
Unable to export new repo from Sat 6.3

### ISSUE THREAD

**Issue by ozchrisishere** [RedHatSatellite/sat6_scripts#37]
Unable to export a repo that has been added in Sat 6.3. Have tested that any repo that was previously subscribed and synced in 6.2 and Satellite upgraded to 6.3 still exports. Any new repo added in 6.3 does not export and fails with permissions errors. 

Export Single_Sign-On_7_2_RHEL_6_Server_RPMs_x86_64                    (FULL)
  Waiting for export to complete...                                    ERROR: /var/sat-export/DIG-Red_Hat_Single_Sign-On-Single_Sign-On_7_2_RHEL_6_Server_RPMs_x86_64/DIG/Library/content/dist/rhel/server/6/6Server/x86_64/rh-sso/7.2/os was not created.
Check permissions/SELinux on export dir

Have given /var/sat-export fill permissions and SELinux in permissive and errors still appear.

**Comment by ggatward** [comment]
Problem is the naming convention used by katello during the export has changed. The export directory now uses the value of 'backend identifier' for each repo rather than the 'label' - for repos created in 6.2 the backend identifier = label so no change.  Exports of new content (created post 6.3 upgrade) are using the new uuid format naming, therefore not being seen as successfully exported by the export_repo function.  The backend identifier can be seen in the WebUI for each repo - so far have not found the hammer/API call to retrieve this info  (once found the fix should be trivial)

root@sat62[/var/sat-export] # ll
total 15369672
drwxr-xr-x. 3 foreman foreman         36 Mar  7 19:01 6e5335fd-219e-4607-949c-ef611b2210f9
drwxr-xr-x. 3 foreman foreman         36 Mar  7 18:59 GatwardIT-Red_Hat_Satellite-Red_Hat_Satellite_6_2_for_RHEL_7_Server_RPMs_x86_64-incremental

root@sat62[/var/sat-export] # tree -d 6e5335fd-219e-4607-949c-ef611b2210f9/
6e5335fd-219e-4607-949c-ef611b2210f9/
└── GatwardIT
    └── Library
        └── content
            └── dist
                └── rhel
                    └── server
                        └── 7
                            └── 7Server
                                └── x86_64
                                    └── sat-maintenance
                                        └── 6
                                            └── os
                                                ├── Packages
                                                │   ├── a
                                                │   ├── f
                                                │   ├── p
                                                │   ├── r
                                                │   └── s
                                                └── repodata

19 directories

root@sat62[/var/sat-export] # tree -d GatwardIT-Red_Hat_Satellite-Red_Hat_Satellite_6_2_for_RHEL_7_Server_RPMs_x86_64-incremental/
GatwardIT-Red_Hat_Satellite-Red_Hat_Satellite_6_2_for_RHEL_7_Server_RPMs_x86_64-incremental/
└── GatwardIT
    └── Library
        └── content
            └── dist
                └── rhel
                    └── server
                        └── 7
                            └── 7Server
                                └── x86_64
                                    └── satellite
                                        └── 6.2
                                            └── os
                                                └── repodata
                                             └── repodata

**Comment by ggatward** [comment]
Merged back to development branch pending release
